Spring:
  application:
    name: DATA-READER
  data:
    mongodb:
      #uri: mongodb+srv://eventsdb:Learn%40IBM123@cluster0.qck5t.mongodb.net/events
      uri: mongodb://testdemofinal:dcBBC8ftPSE7x2UUyskcD5Z8myIFPsdbkuQP7xAMDMovnAYdcrhA8GNxqQr5xedRXoZGDmKCBggufkoZN3b0nw==@testdemofinal.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@testdemofinal@
      database: events
  zipkin:
    base-url: http://127.0.0.1:9411/

server:
  port: 9991

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

