Spring:
  application:
    name: DATA-READER
  data:
    mongodb:
      #uri: mongodb+srv://eventsdb:Learn%40IBM123@cluster0.qck5t.mongodb.net/events
      uri: mongodb://testdemofinal:dcBBC8ftPSE7x2UUyskcD5Z8myIFPsdbkuQP7xAMDMovnAYdcrhA8GNxqQr5xedRXoZGDmKCBggufkoZN3b0nw==@testdemofinal.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@testdemofinal@
      database: events
      #uri: mongodb://apmm-team2-kafka-consumer-poc:ayNnHgEIZ7Xt4CyRe4p6Gjq20rElt4Ds0QiYJ2DMLtreowxFAbCJgj4muttJqr8CMqPKMMOXFUF7qTzXB1vMJw==@apmm-team2-kafka-consumer-poc.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@apmm-team2-kafka-consumer-poc@
      #database: demoDatabase
  zipkin:
    base-url: http://127.0.0.1:9411/

server:
  port: 9991

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

springdoc:
  api-docs:
    enabled: true
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html






