apiVersion : apps/v1
kind: Deployment
metadata:
  name: "vesselschedulerreadercluster-37de"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "vesselschedulerreadercluster-37de"
  template:
    metadata:
      labels:
        app: "vesselschedulerreadercluster-37de"
    spec:
      containers:
        - name: "vesselschedulerreadercluster-37de"
          image: "vesselschedulerconatiner.azurecr.io/vesselschedulerreadercluster"
          ports:
          - containerPort: 9991