apiVersion: v1
kind: Service
metadata:
    name: "vesselschedulerreadercluster-37de"
    labels:
        app: "vesselschedulerreadercluster-37de"
spec:

    ports:
    - port: 9991
      targetPort: 9991
      protocol: TCP
      name: http
    selector:
        app: "vesselschedulerreadercluster-37de"